name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release_please:
    name: release-please
    runs-on: ubuntu-latest
    outputs:
      releaseCreated: ${{ steps.release.outputs.release_created }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/manifest.json

  acknowledge_contributors:
    name: Acknowledge Contributors
    runs-on: ubuntu-latest
    needs: release_please
    if: needs.release_please.outputs.releaseCreated
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
          
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          
      - name: Install dependencies
        run: npm install octokit

      - name: Add contributors to release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scripts/mention-contributors.mjs
        
      - name: Commit updated changelog
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add CHANGELOG.md
          git commit -m "docs: update release notes with contributors" || exit 0
          git push

  npm_publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    environment: npm
    needs: [release_please, acknowledge_contributors]
    if: needs.release_please.outputs.releaseCreated
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
          
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci --ignore-scripts --force --no-fund --no-audit

      - run: npm publish --provenance --access public --tag=next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}